/**:
  ros__parameters:
    wheel_radius: 0.81
    wheel_width: 0.245
    wheel_base: 4.4 # between front wheel center and rear wheel center
    wheel_tread: 1.945 # between left wheel center and right wheel center
    front_overhang: 1.8 # between front wheel center and vehicle front
    rear_overhang: 2.7 # between rear wheel center and vehicle rear
    left_overhang: 0.23 # between left wheel center and vehicle left
    right_overhang: 0.23 # between right wheel center and vehicle right
    vehicle_height: 3.045
    max_steer_angle: 0.70 # [rad]
    base_link_to_imu_x: 2.8
    base_link_to_imu_y: 0.7
    base_link_to_imu_z: 0.2
